name: Promote to prod

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build docker image
        run: docker build -t caisser/docker-react -f Dockerfile.dev .

      - name: Run unit test
        run: docker run -e CI=true caisser/docker-react npm run test -- --coverage

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          # AWS Access Key
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          # AWS Secret Key
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          # AWS Region
          region: us-east-1
          # Beanstalk application name
          application_name: docker-react
          # Beanstalk environment name. If empty a version will be created but not deployed anywhere.
          environment_name: Dockerreact-env
          # Version label for new Beanstalk version
          version_label: ${{ github.sha }}
          # Zip file with the version to deploy. If skipped the action will deploy existing version.
          deployment_package: deploy.zip
          # Whether the action should skip creating a new bucket and use the given one to upload the deployment package to instead. When omitted the actions will (try to) create a new one during deployment.
          existing_bucket_name: elasticbeanstalk-us-east-1-875588974749
