name: Check unit testing

on:
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build docker image
      run: docker build -t caisser/docker-react -f Dockerfile.dev .
      
    - name: Run unit test
      run: docker run -e CI=true caisser/docker-react npm run test -- --coverage
